name: Java CI with Maven

on:
  push:
    branches: 
      - dev # 修改这里，使workflow在push到dev分支时触发

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'maven'

    - name: Validate
      run: mvn validate

    - name: Test
      run: mvn test

  merge_to_main:
    needs: build_and_test # 只有当build_and_test job成功完成后才会运行这个job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "logres_king@126.com"
        git config --global user.name "Logres"

    - name: Merge to main
      run: |
        git switch main
        git merge dev
        git push origin main:main
